"Public compatibility exports loaded on explicit access only (ADR-0001)."

from importlib import import_module

_EXPORTS: dict[str, tuple[str, str]] = {
    "ProjectCase": ("data", "ProjectCase"),
    "OptimizationResult": ("model", "OptimizationResult"),
    "ACConsistencyResult": ("ac_consistency", "ACConsistencyResult"),
    "ActuationArbiter": ("actuation_arbiter", "ActuationArbiter"),
    "HardCapReleaseGuard": ("hard_protection", "HardCapReleaseGuard"),
    "ShanchengSafetyCoordinator": ("execution_coordinator", "ShanchengSafetyCoordinator"),
    "FieldCaseBuilder": ("field_data", "FieldCaseBuilder"),
    "FieldCaseReadiness": ("field_data", "FieldCaseReadiness"),
    "FieldDataNotReadyError": ("field_data", "FieldDataNotReadyError"),
    "MeasurementDirection": ("field_data", "MeasurementDirection"),
    "ActiveMarginReporting": ("shancheng_control", "ActiveMarginReporting"),
    "ActiveRequest": ("shancheng_control", "ActiveRequest"),
    "ArbitratedStationCap": ("control_contracts", "ArbitratedStationCap"),
    "CapIntentAction": ("control_contracts", "CapIntentAction"),
    "ChannelAction": ("shancheng_control", "ChannelAction"),
    "ChannelActuationFeedback": ("shancheng_control", "ChannelActuationFeedback"),
    "CommandDisposition": ("shancheng_control", "CommandDisposition"),
    "CommandEnvelope": ("shancheng_control", "CommandEnvelope"),
    "DeviceStatus": ("shancheng_control", "DeviceStatus"),
    "LegacyCommandFactory": ("shancheng_control", "LegacyCommandFactory"),
    "ControlSignalValidity": ("control_contracts", "SignalValidity"),
    "ReactiveRequest": ("shancheng_control", "ReactiveRequest"),
    "SignalValidity": ("shancheng_control", "SignalValidity"),
    "GroupControlConfig": ("hierarchy_types", "GroupControlConfig"),
    "GroupControlAction": ("hierarchy_types", "GroupControlAction"),
    "GroupControlDecision": ("hierarchy_types", "GroupControlDecision"),
    "GroupControlEvent": ("hierarchy_types", "GroupControlEvent"),
    "GroupControlInput": ("hierarchy_types", "GroupControlInput"),
    "GroupControlState": ("hierarchy_types", "GroupControlState"),
    "GroupControlSupervisor": ("group_control", "GroupControlSupervisor"),
    "GroupTelemetrySnapshot": ("control_contracts", "GroupTelemetrySnapshot"),
    "GroupControlScenarioRecord": ("group_control_scenarios", "GroupControlScenarioRecord"),
    "GroupControlScenarioResult": ("group_control_scenarios", "GroupControlScenarioResult"),
    "PVCurtailmentAllocation": ("hierarchy_types", "PVCurtailmentAllocation"),
    "PVStationAvailability": ("hierarchy_types", "PVStationAvailability"),
    "PVStationControlInput": ("hierarchy_types", "PVStationControlInput"),
    "PVStationCurtailmentCommand": ("hierarchy_types", "PVStationCurtailmentCommand"),
    "PVStationSnapshot": ("control_contracts", "PVStationSnapshot"),
    "PlanningSecurityTrajectory": ("hierarchy_types", "PlanningSecurityTrajectory"),
    "HardProtectionStatus": ("control_contracts", "HardProtectionStatus"),
    "PccSafetyConstraint": ("control_contracts", "PccSafetyConstraint"),
    "ResolvedReverseFlowRisk": ("control_contracts", "ResolvedReverseFlowRisk"),
    "ReverseFlowRiskEstimate": ("control_contracts", "ReverseFlowRiskEstimate"),
    "ResourceSchedule": ("resource_control_contracts", "ResourceSchedule"),
    "ResourceType": ("resource_control_contracts", "ResourceType"),
    "BranchServiceState": ("network_model", "BranchServiceState"),
    "NetworkBranchKind": ("network_model", "NetworkBranchKind"),
    "NetworkBus": ("network_model", "NetworkBus"),
    "NetworkContingency": ("network_model", "NetworkContingency"),
    "NetworkDataProvenance": ("network_model", "NetworkDataProvenance"),
    "NetworkModelError": ("network_model", "NetworkModelError"),
    "NetworkModelV2": ("network_model", "NetworkModelV2"),
    "NetworkOperatingPoint": ("network_scenarios", "NetworkOperatingPoint"),
    "NetworkScenario": ("network_scenarios", "NetworkScenario"),
    "NetworkScenarioBatch": ("network_scenarios", "NetworkScenarioBatch"),
    "NetworkSecurityLimits": ("network_scenarios", "NetworkSecurityLimits"),
    "ScenarioStatus": ("network_scenarios", "ScenarioStatus"),
    "NetworkOperatingMode": ("network_model", "NetworkOperatingMode"),
    "NetworkPhaseModel": ("network_model", "NetworkPhaseModel"),
    "NetworkReadiness": ("network_model", "NetworkReadiness"),
    "NetworkSwitch": ("network_model", "NetworkSwitch"),
    "SeriesBranch": ("network_model", "SeriesBranch"),
    "ShuntCompensator": ("network_model", "ShuntCompensator"),
    "ShuntKind": ("network_model", "ShuntKind"),
    "ShuntOperatingPoint": ("network_model", "ShuntOperatingPoint"),
    "SwitchState": ("network_model", "SwitchState"),
    "TransformerTapChanger": ("network_model", "TransformerTapChanger"),
    "TransformerTapPosition": ("network_model", "TransformerTapPosition"),
    "ReactiveAllocation": ("reactive_execution", "ReactiveAllocation"),
    "ReactiveCapability": ("reactive_execution", "ReactiveCapability"),
    "SafetyAllocationResult": ("control_contracts", "SafetyAllocationResult"),
    "ShanchengCapabilityReport": ("shancheng_control", "ShanchengCapabilityReport"),
    "ShanchengControlAlarm": ("shancheng_control", "ShanchengControlAlarm"),
    "ShanchengControlConfig": ("shancheng_control", "ShanchengControlConfig"),
    "ShanchengControlDecision": ("shancheng_control", "ShanchengControlDecision"),
    "ShanchengControlMode": ("shancheng_control", "ShanchengControlMode"),
    "ShanchengController": ("shancheng_control", "ShanchengController"),
    "ShanchengDispatchCommand": ("shancheng_control", "ShanchengDispatchCommand"),
    "ShanchengSetpoints": ("shancheng_control", "ShanchengSetpoints"),
    "ShanchengTelemetry": ("shancheng_control", "ShanchengTelemetry"),
    "StorageInterlocks": ("shancheng_control", "StorageInterlocks"),
    "StorageTelemetry": ("shancheng_control", "StorageTelemetry"),
    "StationActuationFeedback": ("control_contracts", "StationActuationFeedback"),
    "StationCapIntent": ("control_contracts", "StationCapIntent"),
    "SvgTelemetry": ("shancheng_control", "SvgTelemetry"),
    "ThresholdSnapshot": ("hierarchy_types", "ThresholdSnapshot"),
    "WindSetpoint": ("shancheng_control", "WindSetpoint"),
    "WindTurbineTelemetry": ("shancheng_control", "WindTurbineTelemetry"),
    "build_synthetic_case": ("data", "build_synthetic_case"),
    "audit_line_load_workbook": ("field_data", "audit_line_load_workbook"),
    "build_project_asset_registry": ("field_data", "build_project_asset_registry"),
    "allocate_pv_curtailment": ("group_control", "allocate_pv_curtailment"),
    "calculate_load_change_rate": ("group_control", "calculate_load_change_rate"),
    "calculate_pv_penetration": ("group_control", "calculate_pv_penetration"),
    "calculate_risk_index": ("group_control", "calculate_risk_index"),
    "calculate_thresholds": ("group_control", "calculate_thresholds"),
    "calculate_shancheng_capabilities": ("shancheng_control", "calculate_shancheng_capabilities"),
    "internal_storage_active_to_southbound": (
        "shancheng_control",
        "internal_storage_active_to_southbound",
    ),
    "internal_svg_reactive_to_southbound": (
        "shancheng_control",
        "internal_svg_reactive_to_southbound",
    ),
    "internal_wind_active_to_southbound": (
        "shancheng_control",
        "internal_wind_active_to_southbound",
    ),
    "internal_wind_reactive_to_southbound": (
        "shancheng_control",
        "internal_wind_reactive_to_southbound",
    ),
    "import_short_circuit_workbook": ("field_data", "import_short_circuit_workbook"),
    "run_group_control_scenarios": ("group_control_scenarios", "run_group_control_scenarios"),
    "write_group_control_scenario_outputs": (
        "group_control_scenarios",
        "write_group_control_scenario_outputs",
    ),
    "build_planning_security_trajectories": (
        "planning_security",
        "build_planning_security_trajectories",
    ),
    "build_planning_security_trajectory": (
        "planning_security",
        "build_planning_security_trajectory",
    ),
    "estimate_reverse_flow_probability": ("planning_security", "estimate_reverse_flow_probability"),
    "assess_n_minus_one": ("network_model", "assess_n_minus_one"),
    "assess_network_model": ("network_model", "assess_network_model"),
    "build_network_scenarios": ("network_scenarios", "build_network_scenarios"),
    "evaluate_network_scenarios": ("network_scenarios", "evaluate_network_scenarios"),
    "write_network_scenario_outputs": ("network_scenarios", "write_network_scenario_outputs"),
    "local_shancheng_setpoints": ("shancheng_control", "local_shancheng_setpoints"),
    "northbound_active_target_to_internal": (
        "shancheng_control",
        "northbound_active_target_to_internal",
    ),
    "northbound_reactive_target_to_internal": (
        "shancheng_control",
        "northbound_reactive_target_to_internal",
    ),
    "solve_case_ac_consistent": ("ac_consistency", "solve_case_ac_consistent"),
    "solve_case_misocp": ("misocp_model", "solve_case_misocp"),
    "solve_case": ("model", "solve_case"),
    "write_field_data_audit": ("field_data", "write_field_data_audit"),
    "validate_resource_schedules": ("resource_control_contracts", "validate_resource_schedules"),
    "validate_legacy_network_alignment": ("network_model", "validate_legacy_network_alignment"),
    "allocate_bounded_reactive_power": ("reactive_execution", "allocate_bounded_reactive_power"),
    "calculate_reactive_capabilities": ("reactive_execution", "calculate_reactive_capabilities"),
}

# The legacy export whitelist is resolved by __getattr__; architecture tests verify it.
__all__ = list(_EXPORTS)  # pyright: ignore[reportUnsupportedDunderAll]


def __getattr__(name: str) -> object:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, attribute = _EXPORTS[name]
    value: object = getattr(import_module(f".{module}", __name__), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
