"""Generator v2: Python authority -> OpenAPI, result schema, scoped TS types."""

import argparse
import json
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from oilfield_energy.modules.dispatch.contracts import CoordinationSnapshot, ReferenceEconomics
from oilfield_energy.modules.power_flow.contracts import ClusterValidation
from oilfield_energy.modules.studies.contracts import CommunicationEventExecution, ScenarioEvent
from oilfield_energy.service import SimulationResult
from oilfield_energy.web_api import app


def typescript(schema: dict[str, Any]) -> str:
    """Translate the bounded JSON Schema subset emitted for these cost values."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript(v) for v in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        required = schema.get("required", [])
        return (
            "{ "
            + "; ".join(
                json.dumps(name) + ("" if name in required else "?") + ": " + typescript(value)
                for name, value in schema["properties"].items()
            )
            + " }"
        )
    primitives = {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }
    if kind not in primitives:
        raise ValueError(f"unsupported economic schema node: {schema}")
    return primitives[kind]


def type_bundle(*models: type) -> str:
    definitions = {}
    for model in models:
        schema = TypeAdapter(model).json_schema()
        definitions.update({**schema.get("$defs", {}), model.__name__: schema})
    ts = "// Generated by tools/export_economic_contracts.py v2; do not edit.\n"
    ts += (
        "\n".join(
            f"export type {name} = {typescript(value)};"
            for name, value in sorted(definitions.items())
        )
        + "\n"
    )
    return ts


def artifacts(root: Path) -> dict[Path, str]:
    return {
        root / "contracts/openapi/simulation.openapi.json": json.dumps(
            app.openapi(), ensure_ascii=False, indent=2
        )
        + "\n",
        root / "contracts/simulation/result.schema.json": json.dumps(
            SimulationResult.model_json_schema(), ensure_ascii=False, indent=2
        )
        + "\n",
        root / "web/frontend/shared/api/generated/economics.ts": type_bundle(ReferenceEconomics),
        root / "web/frontend/shared/api/generated/cluster.ts": type_bundle(
            ClusterValidation, CoordinationSnapshot
        ),
        root / "web/frontend/shared/api/generated/study-events.ts": type_bundle(
            CommunicationEventExecution, ScenarioEvent
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in artifacts(Path(__file__).resolve().parents[1]).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"generated contract differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
