"""Generate the v2 flat archive schema from calculation and metadata types."""

import argparse
import json
from importlib.metadata import version
from pathlib import Path

from pydantic import TypeAdapter

from oilfield_energy.modules.studies.contracts import NetworkScenarioSummaryMetadata
from oilfield_energy.network_scenarios import NetworkScenarioBatch


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = TypeAdapter(NetworkScenarioBatch).json_schema(mode="serialization")
    metadata = NetworkScenarioSummaryMetadata.model_json_schema(mode="serialization")
    assert not (set(schema["properties"]) & set(metadata["properties"]))
    schema["properties"].update(metadata["properties"])
    schema["required"] = sorted(set(schema.get("required", [])) | set(metadata["required"]))
    schema["title"] = "NetworkScenarioSummaryV2"
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["additionalProperties"] = False
    schema["x-generator"] = {
        "name": "tools/export_network_scenario_contract.py",
        "version": "1",
        "pydantic_version": version("pydantic"),
    }
    schema["description"] = (
        "Generated by tools/export_network_scenario_contract.py from NetworkScenarioBatch "
        "and NetworkScenarioSummaryMetadata (Pydantic 2); do not edit. "
        "Physical equation, topology, and finite-value checks remain runtime requirements."
    )
    target = (
        Path(__file__).resolve().parents[1] / "contracts/studies/network_scenarios_v2.schema.json"
    )
    rendered = json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
            raise SystemExit("network scenario schema drift")
        print("Network scenario schema matches authoritative types.")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(target)


if __name__ == "__main__":
    main()
