"""Generate frontend types AND runtime schemas from authoritative Python contracts."""

import argparse
import json
from pathlib import Path

from oilfield_energy.job_manager import JobStatus
from oilfield_energy.modules.demo_simulation.contracts import (
    Catalog,
    Command,
    FaultRequest,
    Frame,
    Receipt,
    ResourceAvailability,
)


def artifacts():
    models = (
        Catalog,
        Command,
        FaultRequest,
        Frame,
        Receipt,
        ResourceAvailability,
        JobStatus,
    )
    schemas = {m.__name__: m.model_json_schema() for m in models}
    definitions = {}
    for schema in schemas.values():
        definitions.update(schema.get("$defs", {}))
    definitions.update(schemas)

    def ts(schema):
        if "$ref" in schema:
            return schema["$ref"].rsplit("/", 1)[-1]
        if "const" in schema:
            return json.dumps(schema["const"])
        if "enum" in schema:
            return " | ".join(json.dumps(v) for v in schema["enum"])
        if "anyOf" in schema:
            return " | ".join(ts(v) for v in schema["anyOf"])
        kind = schema.get("type")
        if kind == "array":
            return f"Array<{ts(schema['items'])}>"
        if kind == "object":
            if "properties" in schema:
                return (
                    "{ "
                    + "; ".join(
                        json.dumps(k)
                        + ("" if k in schema.get("required", []) else "?")
                        + ": "
                        + ts(v)
                        for k, v in schema["properties"].items()
                    )
                    + " }"
                )
            return f"Record<string, {ts(schema.get('additionalProperties', {}))}>"
        return {
            "number": "number",
            "integer": "number",
            "boolean": "boolean",
            "string": "string",
            "null": "null",
        }.get(kind, "unknown")

    root = Path(__file__).resolve().parents[1]
    directory = root / "web/frontend/shared/api/generated"
    return {
        directory
        / "demo.ts": "// Generated by tools/generate_demo_contracts.py; do not edit.\n"
        + "\n".join(
            f"export type {name} = {ts(schema)};"
            for name, schema in sorted(definitions.items())
        )
        + "\n",
        directory / "demo.schema.json": json.dumps(
            schemas, indent=2, ensure_ascii=False
        )
        + "\n",
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in artifacts().items():
        if args.check:
            if path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"outdated generated artifact: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
